"use client";

import { useMemo, useState } from "react";
import { ConstraintCard } from "@/components/ConstraintCard";
import { ConstraintFilters } from "@/components/ConstraintFilters";
import { healthcareConstraints } from "@/data/healthcareConstraints";
import {
  categoryOptions,
  getConstraintsWithScores,
  sortAndFilterConstraints
} from "@/lib/constraints";
import type { ConstraintCategory, SortOption } from "@/types/constraint";

export default function Home() {
  const [category, setCategory] = useState<ConstraintCategory | "All">("All");
  const [sortBy, setSortBy] = useState<SortOption>("total_priority_score");

  const scoredConstraints = useMemo(
    () => getConstraintsWithScores(healthcareConstraints),
    []
  );

  const visibleConstraints = useMemo(
    () => sortAndFilterConstraints(scoredConstraints, category, sortBy),
    [category, scoredConstraints, sortBy]
  );

  const averagePriority =
    scoredConstraints.reduce(
      (total, item) => total + item.scores.total_priority_score,
      0
    ) / scoredConstraints.length;

  const averageValidation =
    scoredConstraints.reduce(
      (total, item) => total + item.scores.validation_confidence_score,
      0
    ) / scoredConstraints.length;

  const topOpportunity = scoredConstraints.reduce((top, item) =>
    item.scores.overlooked_opportunity_score >
    top.scores.overlooked_opportunity_score
      ? item
      : top
  );

  const topPriority = scoredConstraints.reduce((top, item) =>
    item.scores.total_priority_score > top.scores.total_priority_score ? item : top
  );

  return (
    <main className="app-shell">
      <header className="page-header">
        <div className="page-header__inner">
          <p className="eyebrow">Constraint Intelligence Engine</p>
          <h1>Economic X-Ray Vision</h1>
          <p className="lede">
            A local-first V1 for spotting healthcare administration friction
            before it becomes visible in traditional outcome metrics.
          </p>
          <div className="measurement-strip" aria-label="What this system measures">
            <span>Delay</span>
            <span>Duplicated work</span>
            <span>Hidden labor waste</span>
            <span>Manual verification</span>
            <span>Idle capacity</span>
          </div>
        </div>
      </header>

      <section className="page-main" aria-label="Constraint intelligence list">
        <section className="intelligence-overview" aria-label="Intelligence overview">
          <div className="overview-copy">
            <p className="section-kicker">V1.1 intelligence layer</p>
            <h2>Rank early friction before it turns into late-stage damage.</h2>
            <p>
              Economic X-Ray Vision scores constraint objects by combining waste
              severity, implementation solvability, AI readiness, and overlooked
              opportunity. The goal is to surface where value is being delayed,
              duplicated, trapped, or underused inside healthcare administration.
            </p>
          </div>

          <div className="priority-panel" aria-label="Highest priority constraint">
            <span>Highest priority constraint</span>
            <strong>{topPriority.title}</strong>
            <p>{topPriority.description}</p>
            <div className="priority-panel__meta">
              <span>{topPriority.category}</span>
              <span>Priority {topPriority.scores.total_priority_score.toFixed(1)}</span>
              <span>
                Validation{" "}
                {topPriority.scores.validation_confidence_score.toFixed(1)}
              </span>
            </div>
          </div>
        </section>

        <div className="summary-grid" aria-label="Portfolio summary metrics">
          <div className="summary-item">
            <span>Industry</span>
            <strong>Healthcare</strong>
          </div>
          <div className="summary-item">
            <span>Objects</span>
            <strong>{scoredConstraints.length}</strong>
          </div>
          <div className="summary-item">
            <span>Average Priority</span>
            <strong>{averagePriority.toFixed(1)}</strong>
          </div>
          <div className="summary-item">
            <span>Average Validation</span>
            <strong>{averageValidation.toFixed(1)}</strong>
          </div>
          <div className="summary-item">
            <span>Top Overlooked Area</span>
            <strong>{topOpportunity.category}</strong>
          </div>
        </div>

        <section className="scoring-model" aria-label="Scoring model explanation">
          <div>
            <p className="section-kicker">Scoring model</p>
            <h2>Deterministic, inspectable ranking</h2>
          </div>
          <p>
            Scores are calculated locally from structured fields, not generated by
            an AI model. Severity weights time, capital, labor, and trend;
            solvability balances digital potential against complexity; AI readiness
            estimates where automation or extraction may help; overlooked opportunity
            rewards high-friction areas with lower visibility. V1.2 adds evidence,
            measurability, and validation confidence scores so each ranking can be
            inspected for defensibility.
          </p>
        </section>

        <ConstraintFilters
          categories={categoryOptions(scoredConstraints)}
          category={category}
          resultCount={visibleConstraints.length}
          sortBy={sortBy}
          onCategoryChange={setCategory}
          onSortChange={setSortBy}
        />

        <div className="constraint-list">
          {visibleConstraints.map((constraint) => (
            <ConstraintCard constraint={constraint} key={constraint.id} />
          ))}
        </div>

        {visibleConstraints.length === 0 ? (
          <div className="empty-state">No constraint objects match this filter.</div>
        ) : null}
      </section>
    </main>
  );
}
